#!/bin/sh

USAGE='[help]'
LONG_USAGE='git qa help
        print this long help message.
git qa
        push the current branch to qa environment.'

OPTIONS_SPEC=
. git-sh-setup


qa_push () {
  branch=$(git rev-parse --abbrev-ref HEAD)
  if test "$branch" = "qa_branch"
  then
    die "you need push to qa environment other branch"
  else
    git checkout qa_branch && git reset --hard ${branch} && git push origin qa_branch -f && git checkout ${branch}
  fi
}

case "$#" in
0)
	qa_push "$@" ;;
*)
	cmd="$1"
  shift
	case "$cmd" in
  help)
		git qa -h ;;
  *)
		usage ;;
	esac
esac
